# ==================================
# Base Configuration (အခြေခံ Configuration)
# ==================================
name = "envpn"  # wrangler.jsonc က name ကို ယူသုံးထားပါတယ်။
main = "en-worker.js"
compatibility_date = "2025-11-09"

# ==================================
# KV Namespace Binding
# ==================================
[[kv_namespaces]]
binding = "LICENSES"
id = "d13dc3b292084977b99cfbc18634c8b1"
